name: Compile JSON to Binary Rule-Set

on:
  push:
    paths:
      - 'Rule/*.json'  # 仅在 JSON 文件更新时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile JSON to SRS
      run: |
        chmod +x Singbox/sing-box  # 确保可执行权限
        # 遍历 Rule 目录下所有 .json 文件并编译为 .srs
        for json_file in Rule/*.json; do
          srs_file="${json_file%.json}.srs"  # 将 .json 扩展名替换为 .srs
          Singbox/sing-box rule-set compile --output "$srs_file" "$json_file"
        done

    - name: Commit and Push compiled files if there are any
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add Rule/*.srs
        
        # 仅在有更改时才进行提交和推送
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m 'Compile JSON to SRS'
          git push
