name: Convert TXT to JSON

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: "0 6 * * *"

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run Python script to convert TXT to JSON
      run: |
        python Script/convert_txt_to_json.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add Rule/*.json
        git commit -m 'Convert TXT to JSON'
        git push
