name: Convert TXT to JSON

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: "30 22 * * *" # 6:30 AM UTC+8
  push:
    paths:
      - 'Rule/*.txt'  # 仅当 Rule 文件夹内的 .txt 文件发生更改时触发

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run Python script to convert TXT to JSON
      run: |
        python Script/convert_txt_to_json.py

    - name: Commit and Push changes if there are any
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add Rule/*.json
        
        # 仅在有更改时才进行提交和推送
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m 'Convert TXT to JSON'
          git push
        fi
