name: Delete old workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
# Run monthly, at 00:00 on the 1st day of month.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 默认的 GITHUB_TOKEN
          repository: ${{ github.repository }}
          retain_days: 5
